DEEPSORT:
  MODEL_TYPE: "osnet_x_25"
  MAX_DIST: 0.2 # matching threshold
  MAX_IOU_DISTANCE: 0.7 # Gating threshold
  MAX_AGE: 30 # number of missed misses before a track is deleted
  N_INIT: 3 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100 #  size of the appearance descriptors
